### ISSUE TITLE
synology

### ISSUE THREAD

**Issue by partymike** [dockhippie/watchtower#2]
was using your docker watchtower build on a synology running dsm 6.1 it worked as you could set the variable to the older api of 1.23 (synology running this build currently)...

I can see you have updated the build which has broken this variable....any idea how to update it to work again?

was using: docker run -d -e DOCKER_API_VERSION="1.23" -v /volume1/docker/docker.sock:/var/run/docker.sock webhippie/watchtower

**Comment by tboerger** [comment]
I have just adopted the latest variable changes, you can use the environment variable `WATCHTOWER_APIVERSION` to set the API version.

**Comment by partymike** [comment]
unfortunately i get the following error when running the docker with the "WATCHTOWER_APIVERSION="1.23"" :
----
"time="2017-05-03T07:13:30Z" level=fatal msg="flag provided but not defined: -apiversion" 
stderr
07:13:31
Incorrect Usage. flag provided but not defined: -apiversion"
----
so something has changed, maybe a different switch command? 

Any help would be gratefully received.

**Comment by tboerger** [comment]
I'm very sorry that I have broken the image, I will fix that directly.

**Comment by tboerger** [comment]
I have dropped the `WATCHTOWER_APIVERSION` variable with 14be4b9 again, looks like watchtower provides the environment variable `DOCKER_API_VERSION ` to override the default of `1.24`. If this still fails to launch this looks like an upstream issue since I'm not touching this variable.

**Comment by partymike** [comment]
gives me the error:
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
----
when using the "DOCKER_API_VERSION="1.23""

I couldn't use the v2tec version for this reason as they hardcode api to be 1.24, which was what made your version such a good find with the override.

Thanks for looking anyhow

**Comment by tboerger** [comment]
Damn, I'm really sorry. This container is just using v2tec, but it had been an older version that have been updated.

**Comment by Veldkornet** [comment]
Damn, I have the same problem :(

**Comment by tboerger** [comment]
> Damn, I have the same problem :(

Please file an issue upstream with more details!

**Comment by tboerger** [comment]
AFAIK it should work of DOCKER_API_VERSION gets defined with a proper value. If the issue still exists please ping me again.
