### ISSUE TITLE
arm32 and arm64 images

### ISSUE THREAD

**Issue by bradrydzewski** [dockhippie/watchtower#4]
there is no official arm32 or arm64 watchtower image, but perhaps this is something you could provide since you are building with drone? :)

**Comment by tboerger** [comment]
Yeah, I'm slowly working through the list of my images to migrate it to multi arch drone. If you need it I can build it next.

**Comment by bradrydzewski** [comment]
I do need the image. I was going to build it myself but then I remembered you publish a bunch of images under the webhippie namespace so I was hoping I could take advantage of your distributions 😄

**Comment by tboerger** [comment]
I have published images for arm32v6 and arm64v8 now.
